### ISSUE TITLE
Ruby SDK: Add delete method

### ISSUE THREAD

**Issue by itsmehul** [seamapi/ruby-legacy#21]
```
      # TODO: Add delete method
```

https://github.com/seamapi/ruby/blob/e2dfb797a134bf4f50501eae53a553e15ef1e53f/lib/seam/clients/connected_accounts.rb#L7

**Comment by dawnho** [comment]
lez do this later

**Comment by DebbieAtSeam** [comment]
@dawnho: Should this issue get revisited soon?
